### ISSUE TITLE
all points y value undefined!

### ISSUE THREAD

**Issue by IT-Berater** [orhun/rtl_map#3]
Hi,

compile and link works fine. No output, see:

rtl_map -f 109000000
[18:48:25] INFO Starting rtl_map ~
[18:48:25] INFO Found 1 device(s):
[18:48:25] INFO #0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[18:48:25] INFO Using device: #0
[18:48:25] INFO Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
[18:48:25] INFO Gain set to 2.7
[18:48:25] INFO Center frequency set to 109000000 Hz.
[18:48:25] INFO Sampling at 2048000 S/s
Allocating 15 zero-copy buffers
[18:48:26] INFO Creating FFT graph from samples using gnuplot...
[18:48:26] INFO Done, exiting...
Warning: empty x range [-1.04858e+06:-1.04858e+06], adjusting to [-1.05906e+06:-1.03809e+06]

gnuplot> plot '-' smooth frequency with linespoints lt -1 notitle
                                                                 ^
         line 513: all points y value undefined!

This is the capture.dat

cat capture.dat
1	21.548365
2	6.276362
3	9.542425
4	10.146918
5	10.979499
6	8.996703
7	9.978176
8	9.672492
9	10.635524
10	11.662192
11	9.064567
12	5.000000
13	10.322289
14	9.064567
15	9.956130
16	10.865932
17	9.130374
18	0.000000
19	10.993285
20	4.771213
21	8.010300
22	5.000000
23	6.989700
24	7.592570
25	6.276362
26	2.385606
27	3.494850
28	-inf
29	5.000000
30	5.395906
31	5.880456
32	6.989700
33	9.404068
34	8.854260
35	7.841009
36	7.456809
37	3.494850
38	5.880456
39	5.395906
40	6.276362
41	7.841009
42	6.393768
43	7.385606
44	6.505150
45	3.494850
46	3.890756
47	8.217263
48	4.515450
49	4.225490
50	5.395906
51	3.890756
52	2.385606
53	2.385606
54	2.385606
55	-inf
56	1.505150
57	3.010300
58	0.000000
59	2.385606
60	-inf
61	-inf
62	-inf
63	-inf
64	-inf
65	-inf
66	-inf
67	-inf
68	-inf
69	-inf
70	0.000000
71	-inf
72	-inf
73	0.000000
74	-inf
75	5.206964
76	3.890756
77	3.494850
78	6.276362
79	6.712113
80	-inf
81	3.494850
82	5.395906
83	-inf
84	4.225490
85	2.385606
86	7.898918
87	4.771213
88	7.156819
89	8.961958
90	7.156819
91	5.569717
92	7.781513
93	6.020600
94	11.215190
95	7.592570
96	5.395906
97	-inf
98	6.808640
99	8.450980
100	11.439009
101	5.395906
102	8.010300
103	11.682299
104	10.226615
105	9.595390
106	6.611096
107	10.021606
108	5.395906
109	8.406206
110	10.064186
111	4.515450
112	11.882885
113	8.313789
114	10.865932
115	12.235790
116	10.043000
117	11.505150
118	6.901056
119	-inf
120	10.894885
121	4.225490
122	8.116246
123	12.442754
124	10.894885
125	9.194245
126	5.569717
127	10.226615
128	13.251537
129	12.644584
130	13.360489
131	10.431799
132	5.880456
133	9.621396
134	11.416506
135	13.079750
136	8.854260
137	5.000000
138	11.864560
139	-inf
140	8.116246
141	12.799533
142	11.472331
143	13.764082
144	12.512136
145	10.085167
146	13.760242
147	6.611096
148	12.180813
149	10.635524
150	7.781513
151	12.505296
152	9.316614
153	12.334338
154	13.085002
155	14.672492
156	11.177642
157	8.854260
158	14.833055
159	12.041200
160	10.569716
161	3.890756
162	9.542425
163	11.827440
164	15.522435
165	10.667694
166	12.484648
167	10.431799
168	12.258932
169	14.191096
170	12.612221
171	10.536050
172	13.721465
173	8.890757
174	10.602870
175	0.000000
176	12.421499
177	10.806840
178	6.611096
179	14.395479
180	14.280622
181	11.989700
182	12.887459
183	14.561110
184	7.156819
185	10.635524
186	2.385606
187	10.937604
188	13.653912
189	6.989700
190	0.000000
191	8.116246
192	7.781513
193	10.322289
194	10.761441
195	11.692283
196	12.714128
197	4.515450
198	9.865640
199	13.993253
200	12.799533
201	13.464234
202	11.928031
203	9.346159
204	11.882885
205	11.537480
206	10.993285
207	11.721961
208	12.846869
209	11.370790
210	11.312256
211	14.756688
212	10.536050
213	10.064186
214	12.400035
215	13.031907
216	11.864560
217	13.069209
218	11.324089
219	10.467109
220	10.651669
221	8.313789
222	11.760913
223	12.007003
224	12.835132
225	13.266063
226	10.715075
227	9.432453
228	8.926649
229	8.313789
230	1.505150
231	6.808640
232	5.395906
233	9.097720
234	10.246090
235	9.542425
236	7.657394
237	10.265392
238	6.901056
239	12.982985
240	2.385606
241	10.894885
242	12.512136
243	11.494266
244	10.519018
245	11.631680
246	6.393768
247	10.146918
248	12.631697
249	11.494266
250	10.413927
251	10.651669
252	9.542425
253	11.416506
254	10.467109
255	9.746950
256	6.393768
257	21.548365
258	6.276362
259	9.542425
260	10.146918
261	10.979499
262	8.996703
263	9.978176
264	9.672492
265	10.635524
266	11.662192
267	9.064567
268	5.000000
269	10.322289
270	9.064567
271	9.956130
272	10.865932
273	9.130374
274	0.000000
275	10.993285
276	4.771213
277	8.010300
278	5.000000
279	6.989700
280	7.592570
281	6.276362
282	2.385606
283	3.494850
284	-inf
285	5.000000
286	5.395906
287	5.880456
288	6.989700
289	9.404068
290	8.854260
291	7.841009
292	7.456809
293	3.494850
294	5.880456
295	5.395906
296	6.276362
297	7.841009
298	6.393768
299	7.385606
300	6.505150
301	3.494850
302	3.890756
303	8.217263
304	4.515450
305	4.225490
306	5.395906
307	3.890756
308	2.385606
309	2.385606
310	2.385606
311	-inf
312	1.505150
313	3.010300
314	0.000000
315	2.385606
316	-inf
317	-inf
318	-inf
319	-inf
320	-inf
321	-inf
322	-inf
323	-inf
324	-inf
325	-inf
326	0.000000
327	-inf
328	-inf
329	0.000000
330	-inf
331	5.206964
332	3.890756
333	3.494850
334	6.276362
335	6.712113
336	-inf
337	3.494850
338	5.395906
339	-inf
340	4.225490
341	2.385606
342	7.898918
343	4.771213
344	7.156819
345	8.961958
346	7.156819
347	5.569717
348	7.781513
349	6.020600
350	11.215190
351	7.592570
352	5.395906
353	-inf
354	6.808640
355	8.450980
356	11.439009
357	5.395906
358	8.010300
359	11.682299
360	10.226615
361	9.595390
362	6.611096
363	10.021606
364	5.395906
365	8.406206
366	10.064186
367	4.515450
368	11.882885
369	8.313789
370	10.865932
371	12.235790
372	10.043000
373	11.505150
374	6.901056
375	-inf
376	10.894885
377	4.225490
378	8.116246
379	12.442754
380	10.894885
381	9.194245
382	5.569717
383	10.226615
384	13.251537
385	12.644584
386	13.360489
387	10.431799
388	5.880456
389	9.621396
390	11.416506
391	13.079750
392	8.854260
393	5.000000
394	11.864560
395	-inf
396	8.116246
397	12.799533
398	11.472331
399	13.764082
400	12.512136
401	10.085167
402	13.760242
403	6.611096
404	12.180813
405	10.635524
406	7.781513
407	12.505296
408	9.316614
409	12.334338
410	13.085002
411	14.672492
412	11.177642
413	8.854260
414	14.833055
415	12.041200
416	10.569716
417	3.890756
418	9.542425
419	11.827440
420	15.522435
421	10.667694
422	12.484648
423	10.431799
424	12.258932
425	14.191096
426	12.612221
427	10.536050
428	13.721465
429	8.890757
430	10.602870
431	0.000000
432	12.421499
433	10.806840
434	6.611096
435	14.395479
436	14.280622
437	11.989700
438	12.887459
439	14.561110
440	7.156819
441	10.635524
442	2.385606
443	10.937604
444	13.653912
445	6.989700
446	0.000000
447	8.116246
448	7.781513
449	10.322289
450	10.761441
451	11.692283
452	12.714128
453	4.515450
454	9.865640
455	13.993253
456	12.799533
457	13.464234
458	11.928031
459	9.346159
460	11.882885
461	11.537480
462	10.993285
463	11.721961
464	12.846869
465	11.370790
466	11.312256
467	14.756688
468	10.536050
469	10.064186
470	12.400035
471	13.031907
472	11.864560
473	13.069209
474	11.324089
475	10.467109
476	10.651669
477	8.313789
478	11.760913
479	12.007003
480	12.835132
481	13.266063
482	10.715075
483	9.432453
484	8.926649
485	8.313789
486	1.505150
487	6.808640
488	5.395906
489	9.097720
490	10.246090
491	9.542425
492	7.657394
493	10.265392
494	6.901056
495	12.982985
496	2.385606
497	10.894885
498	12.512136
499	11.494266
500	10.519018
501	11.631680
502	6.393768
503	10.146918
504	12.631697
505	11.494266
506	10.413927
507	10.651669
508	9.542425
509	11.416506
510	10.467109
511	9.746950
512	6.393768

**Comment by IT-Berater** [comment]
What ist **-inf** in capture.dat?

**Comment by orhun** [comment]
It's about fftw3 library. Still working on that.
Can you try it with -M parameter?

**Comment by orhun** [comment]
Also please see https://github.com/KeyLo99/rtl_map/issues/2#issuecomment-460003536 about this issue.

**Comment by IT-Berater** [comment]
I have only a headless Raspberry Pi without display. I will build a gnugraph from file.

rtl_map -f 109000000 -M
[19:07:55] INFO Starting rtl_map ~
[19:07:55] INFO Found 1 device(s):
[19:07:55] INFO #0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[19:07:56] INFO Using device: #0
[19:07:56] INFO Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
[19:07:56] INFO Gain set to 2.7
[19:07:56] INFO Center frequency set to 109000000 Hz.
[19:07:56] INFO Sampling at 2048000 S/s
Allocating 15 zero-copy buffers
[19:07:56] INFO Creating FFT graph from samples using gnuplot...
[19:07:56] INFO Done, exiting...
Warning: empty x range [2.14644e+09:2.14644e+09], adjusting to [2.12497e+09:2.1679e+09]
Warning: empty y range [0:0], adjusting to [-1:1]
QXcbConnection: Could not connect to display

**Comment by orhun** [comment]
Okay, it looks like fftw3 library is not working well. (-inf values or empty x and y ranges.)
Did you check FFTW_MEASURE parameter in code? Which version of rtl_map are you using?

**Comment by IT-Berater** [comment]
No Version String (rtl_map -h) found:

rtl_map -h
rtl_map, a FFT-based visualizer for RTL-SDR devices. (RTL2832/DVB-T)

Usage:	[-d device index (default: 0)]
	[-s sample rate (default: 2048000 Hz)]
	[-f center frequency (Hz)] *
	[-g gain (0 for auto) (default: ~1-3)]
	[-r refresh rate for -C read (default: 500ms)]
	[-D don't show gnuplot graph (default: show)]
	[-C continuously read samples (default: off)]
	[-M show magnitude graph (default graph: dB)]
	[-O disable offset tuning (default: on)]
	[-T turn off log colors (default: on)]
	[-h show this help message and exit]
	[filename (a '-' dumps samples to stdout)]

**Comment by IT-Berater** [comment]
I have the sourcecode status of today.

**Comment by IT-Berater** [comment]
echo $FFTW_MEASURE is ""

**Comment by orhun** [comment]
I was talking about https://github.com/KeyLo99/rtl_map/blob/master/rtl_map.c#L360

**Comment by orhun** [comment]
If the code is up-to-date, everything looks fine actually.
You might try to fix it with uninstalling and installing fftw lib or trying a different usb port.
I'm definitely gonna check this issue within a few hours.
Please keep me updated!

**Comment by IT-Berater** [comment]
I try a different usb port, in line 17 and others are -inf ...

tl_map -f 109000000 -D -
[19:49:59] INFO Starting rtl_map ~
[19:49:59] INFO Found 1 device(s):
[19:49:59] INFO #0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[19:50:00] INFO Using device: #0
[19:50:00] INFO Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
[19:50:00] INFO Gain set to 2.7
[19:50:00] INFO Center frequency set to 109000000 Hz.
[19:50:00] INFO Sampling at 2048000 S/s
Allocating 15 zero-copy buffers
[19:50:00] INFO Reading samples...
1	21.282387
2	9.672492
3	11.359208
4	10.806840
5	11.590317
6	6.020600
7	12.220224
8	5.880456
9	12.498435
10	7.525750
11	12.938555
12	7.311990
13	8.313789
14	2.385606
15	12.726536
16	9.488135
17	-inf
18	5.395906
19	3.494850
20	10.993285
21	11.347565
22	6.808640
...
48	5.000000
49	3.010300
50	4.771213
51	-inf
52	1.505150
53	-inf
54	4.225490
55	2.385606
56	-inf
57	3.890756
58	1.505150
59	0.000000
60	-inf
61	-inf
62	-inf
63	-inf
64	-inf
65	-inf
66	-inf
67	-inf
68	-inf
69	1.505150
70	0.000000
71	1.505150
72	2.385606
73	1.505150
74	3.010300
75	1.505150
...

**Comment by orhun** [comment]
Like I said it's a common problem with fftw.
-M param will create magnitude graph from samples.
So 0 value would not be a problem with gnuplot for now...

**Comment by IT-Berater** [comment]
Ok, thanks, -M Parameter works fine:

rtl_map -M -f 109000000 -D capture-1090.dat
[20:14:49] INFO Starting rtl_map ~
[20:14:49] INFO Found 1 device(s):
[20:14:49] INFO #0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
[20:14:50] INFO Using device: #0
[20:14:50] INFO Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
[20:14:50] INFO Gain set to 2.7
[20:14:50] INFO Center frequency set to 109000000 Hz.
[20:14:50] INFO Sampling at 2048000 S/s
Allocating 15 zero-copy buffers
[20:14:50] INFO Reading samples...
[20:14:50] INFO Done, exiting...
pi@pi-home:~ $ cat capture-1090.dat
1	116.674759
2	11.090536
3	7.810250
4	5.744563
5	12.369317
6	12.845233
7	12.609520
8	4.582576
9	5.916080
10	10.677078
11	10.344080
12	2.000000
13	21.954498
14	10.954452
15	8.246211
16	5.656854
17	17.888544
18	14.247807
19	6.000000
20	10.583005
21	7.874008
22	9.643651
23	7.810250
24	3.162278
25	2.236068
26	10.000000
27	12.288206
28	5.477226
29	6.633250
30	14.764823
31	2.645751
32	5.196152
33	7.280110
34	9.539392
35	12.569805
36	5.830952
37	4.242640
38	10.295630
39	2.828427
40	7.000000
41	2.000000
42	9.165152
43	7.615773
44	4.472136
45	5.196152
46	0.000000
47	7.000000
48	3.741657
49	5.196152
50	1.414214
51	0.000000
52	1.000000
53	0.000000
54	1.732051
55	0.000000
56	1.732051
57	0.000000
58	1.414214
59	0.000000
60	1.414214
61	1.414214
62	1.000000
63	1.414214
64	1.000000
65	1.000000
66	0.000000
67	0.000000
68	1.000000
69	0.000000
70	1.000000
71	1.414214
72	1.732051
73	1.732051
74	1.414214
75	2.828427
76	0.000000
77	3.872983
78	3.872983
79	1.000000
80	2.000000
81	2.000000
82	4.123106
83	1.000000
84	1.000000
85	0.000000
86	2.449490
87	2.000000
88	2.449490
89	4.795832
90	6.708204
91	5.656854
92	5.656854
93	4.358899
94	4.582576
95	7.810250
96	4.898980
97	3.741657
98	6.244998
99	7.483315
100	4.242640
101	5.830952
102	8.366600
103	7.071068
104	7.141428
105	13.038404
106	7.071068
107	1.732051
108	10.000000
109	7.000000
110	9.797959
111	10.344080
112	11.313708
113	18.466185
114	6.244998
115	2.449490
116	7.483315
117	8.306623
118	14.177447
119	9.433981
120	13.820275
121	10.198039
122	5.656854
123	0.000000
124	15.684387
125	6.782330
126	8.774964
127	25.337719
128	6.164414
129	5.000000
130	4.898980
131	27.982138
132	9.000000
133	8.366600
134	17.000000
135	0.000000
136	7.937254
137	11.269427
138	16.522711
139	13.490738
140	17.029387
141	9.695360
142	8.888194
143	5.385165
144	9.848858
145	29.342802
146	17.320509
147	17.521416
148	14.899665
149	11.445523
150	15.556349
151	5.291502
152	13.784049
153	26.495283
154	11.789826
155	16.155495
156	15.165751
157	13.000000
158	11.532562
159	14.798649
160	12.727922
161	11.445523
162	9.591663
163	20.024984
164	14.730920
165	14.662878
166	15.874508
167	14.832397
168	23.366642
169	14.966630
170	9.695360
171	5.291502
172	8.888194
173	2.828427
174	6.928203
175	10.295630
176	25.000000
177	9.055386
178	10.295630
179	1.732051
180	24.494898
181	19.697716
182	7.681146
183	17.606817
184	13.228757
185	19.467922
186	23.600847
187	12.083046
188	0.000000
189	26.981476
190	2.645751
191	13.453624
192	5.196152
193	3.605551
194	10.148891
195	19.849434
196	3.000000
197	21.260292
198	12.328828
199	8.062258
200	7.416198
201	14.035668
202	8.485281
203	16.248077
204	6.244998
205	6.557438
206	12.529964
207	3.872983
208	14.456832
209	25.748787
210	15.905973
211	26.683329
212	8.426149
213	21.377558
214	19.748417
215	25.317978
216	30.347982
217	4.472136
218	19.339079
219	9.000000
220	29.478806
221	15.099669
222	14.035668
223	30.838287
224	25.039968
225	15.297058
226	11.661903
227	7.280110
228	30.099834
229	16.462078
230	9.797959
231	26.172504
232	20.688160
233	6.480741
234	6.633250
235	11.958261
236	15.099669
237	12.961481
238	19.104973
239	11.445523
240	20.099751
241	26.645824
242	9.000000
243	13.266500
244	16.093477
245	28.035692
246	3.605551
247	14.212670
248	12.409674
249	8.831760
250	4.000000
251	13.784049
252	12.961481
253	12.165525
254	5.000000
255	9.695360
256	11.135529
257	116.674759
258	11.090536
259	7.810250
260	5.744563
261	12.369317
262	12.845233
263	12.609520
264	4.582576
265	5.916080
266	10.677078
267	10.344080
268	2.000000
269	21.954498
270	10.954452
271	8.246211
272	5.656854
273	17.888544
274	14.247807
275	6.000000
276	10.583005
277	7.874008
278	9.643651
279	7.810250
280	3.162278
281	2.236068
282	10.000000
283	12.288206
284	5.477226
285	6.633250
286	14.764823
287	2.645751
288	5.196152
289	7.280110
290	9.539392
291	12.569805
292	5.830952
293	4.242640
294	10.295630
295	2.828427
296	7.000000
297	2.000000
298	9.165152
299	7.615773
300	4.472136
301	5.196152
302	0.000000
303	7.000000
304	3.741657
305	5.196152
306	1.414214
307	0.000000
308	1.000000
309	0.000000
310	1.732051
311	0.000000
312	1.732051
313	0.000000
314	1.414214
315	0.000000
316	1.414214
317	1.414214
318	1.000000
319	1.414214
320	1.000000
321	1.000000
322	0.000000
323	0.000000
324	1.000000
325	0.000000
326	1.000000
327	1.414214
328	1.732051
329	1.732051
330	1.414214
331	2.828427
332	0.000000
333	3.872983
334	3.872983
335	1.000000
336	2.000000
337	2.000000
338	4.123106
339	1.000000
340	1.000000
341	0.000000
342	2.449490
343	2.000000
344	2.449490
345	4.795832
346	6.708204
347	5.656854
348	5.656854
349	4.358899
350	4.582576
351	7.810250
352	4.898980
353	3.741657
354	6.244998
355	7.483315
356	4.242640
357	5.830952
358	8.366600
359	7.071068
360	7.141428
361	13.038404
362	7.071068
363	1.732051
364	10.000000
365	7.000000
366	9.797959
367	10.344080
368	11.313708
369	18.466185
370	6.244998
371	2.449490
372	7.483315
373	8.306623
374	14.177447
375	9.433981
376	13.820275
377	10.198039
378	5.656854
379	0.000000
380	15.684387
381	6.782330
382	8.774964
383	25.337719
384	6.164414
385	5.000000
386	4.898980
387	27.982138
388	9.000000
389	8.366600
390	17.000000
391	0.000000
392	7.937254
393	11.269427
394	16.522711
395	13.490738
396	17.029387
397	9.695360
398	8.888194
399	5.385165
400	9.848858
401	29.342802
402	17.320509
403	17.521416
404	14.899665
405	11.445523
406	15.556349
407	5.291502
408	13.784049
409	26.495283
410	11.789826
411	16.155495
412	15.165751
413	13.000000
414	11.532562
415	14.798649
416	12.727922
417	11.445523
418	9.591663
419	20.024984
420	14.730920
421	14.662878
422	15.874508
423	14.832397
424	23.366642
425	14.966630
426	9.695360
427	5.291502
428	8.888194
429	2.828427
430	6.928203
431	10.295630
432	25.000000
433	9.055386
434	10.295630
435	1.732051
436	24.494898
437	19.697716
438	7.681146
439	17.606817
440	13.228757
441	19.467922
442	23.600847
443	12.083046
444	0.000000
445	26.981476
446	2.645751
447	13.453624
448	5.196152
449	3.605551
450	10.148891
451	19.849434
452	3.000000
453	21.260292
454	12.328828
455	8.062258
456	7.416198
457	14.035668
458	8.485281
459	16.248077
460	6.244998
461	6.557438
462	12.529964
463	3.872983
464	14.456832
465	25.748787
466	15.905973
467	26.683329
468	8.426149
469	21.377558
470	19.748417
471	25.317978
472	30.347982
473	4.472136
474	19.339079
475	9.000000
476	29.478806
477	15.099669
478	14.035668
479	30.838287
480	25.039968
481	15.297058
482	11.661903
483	7.280110
484	30.099834
485	16.462078
486	9.797959
487	26.172504
488	20.688160
489	6.480741
490	6.633250
491	11.958261
492	15.099669
493	12.961481
494	19.104973
495	11.445523
496	20.099751
497	26.645824
498	9.000000
499	13.266500
500	16.093477
501	28.035692
502	3.605551
503	14.212670
504	12.409674
505	8.831760
506	4.000000
507	13.784049
508	12.961481
509	12.165525
510	5.000000
511	9.695360
512	11.135529

**Comment by IT-Berater** [comment]
My first Map:
![capture-1090](https://user-images.githubusercontent.com/1748499/52182570-ab434600-27fe-11e9-9e41-a0a445b8f6dd.png)

**Comment by orhun** [comment]
That's nice :+1:

**Comment by IT-Berater** [comment]
Here the gnuplot script:

set title "Frequenzdiagramm mit rtl-map"
set ylabel "Amplitude (dB)"
set xlabel "Messungen mitFrequenz 1090 Mhz"
set terminal png
set xrange [0:500]
set output "capture-1090.png"
plot "capture-1090.dat" using 1:2 title "rtl Sensor" with lines

**Comment by IT-Berater** [comment]
![capture-1090](https://user-images.githubusercontent.com/1748499/52182704-0295e600-2800-11e9-8cb9-f1506e8e6ca5.png)
