### ISSUE TITLE
khz in README.md 

### ISSUE THREAD

**Issue by IT-Berater** [orhun/rtl_map#4]
Hi,

in the Readme.md file are the x label from the graph is khz. 

It is Mhz!?

**Comment by orhun** [comment]
Yeah, you are right...
I'm gonna fix it ASAP.
Thanks.

**Comment by orhun** [comment]
Solved with latest commits: 71c8c105b8873fcba625567a37c2cacb12de2800 8222acfa6beed96d40c9e010673fc259e5a7e83c d4c81bb22904c888436e5ad229334dd1f9898a89
